print('===== Desafio 4b=====')
r = input('Digite qual quer coisa: ')
print ('O tipo primitivo desse valor é ', type(r))
print ('Tem espaço ? ', r.isspace())
print ('É numero ? ', r.isnumeric())
print ('É letra ? ', r.isalpha())
print ('É alfanumerico ? ', r.isalnum())
print ('Está em maiuscula ? ', r.isupper())
print ('Está em minuscula ? ', r.islower())
print ('Está capitalizada ? ', r.istitle())