times = ('BOTAFOGO', 'GRÊMIO', 'FLAMENGO', 'PALMEIRAS', 'ATHLETICO-PR', 'SÃO PAULO', 'FLUMINENSE', 'RED BULL BRAGANTINO', 'FORTALEZA', 'INTERNACIONAL', 'CRUZEIRO', 'CUIABÁ', 'ATLÉTICO-MG', 'SANTOS', 'CORINTHIANS', 'GOIÁS', 'BAHIA', 'CORITIBA', 'AMÉRICA-MG', 'VASCO')
print('-=-' * 30)
print(f'Lista de times do Brasileirão: {times}')
print('-=-' * 30)
print(f'Os 5 primeiros são {times[0:5]}')
print('-=-' * 30)
print(f'Os últimos 4 colocados são {times[-4:]}')
print('-=-' * 30)
print(f'Os times em ordem alfabetica: {sorted(times)}')
print('-=-' * 30)
print(f'O RED BULL BRAGANTINA está na {times.index("RED BULL BRAGANTINO")+1}° posição')